### ISSUE TITLE
Could not save payload: 'gbk' codec can't encode character '\xff' in position 170: illegal multibyte sequence , please help me , why ?

### ISSUE THREAD

**Issue by ss3931** [Moopinger/CLZero#4]
[-]Could not save payload: 'gbk' codec can't encode character '\xff' in position 170: illegal multibyte sequence
[+] https://218.202.XXX.XXX:4443 may be vulnerable.
[+] Smuggle type: xprespace-ff
[+]Payload saved to ./payloads/218_202_XXX_XXX:4443xprespace_ff.txt

**Comment by Moopinger** [comment]
Hi there, 

%ff is a non printable character so it seems to have issues writing it to a file. I will need to add add some sort of additional encoding for this at some point. For now, You can still test the vulnerable endpoint in Burp using the burp encoder to hold the value for %FF
